# Generated by Django 4.1.7 on 2023-03-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0002_alter_user_managers_remove_user_passwored2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
