# Generated by Django 4.1.7 on 2023-03-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
