# Generated by Django 4.1.7 on 2023-03-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0007_alter_user_options_usertoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
